---
- hosts: all

  tasks:
    - fail:
        msg: "Old setup with self-signed certs. Fix first. Without domain you get a lot of problems."

    - name: Ensure azure_key is set
      when: azure_key is undefined or azure_key == ''
      fail:
        msg: "'azure_key' must be provided"

    - name: Install dependencies
      apt:
        state: present
        update_cache: yes
        name:
          - python3-pip
          - libc6
          - libpthread-stubs0-dev
          - ca-certificates
          - libasound2

    - name: Clone repo and install dependencies
      shell: |
        set -e
        
        rm -rf /root/ch 
        git clone https://github.com/jihadichan/ch.git /root/ch
        
        cd /root/ch && pip install -r requirements.txt
        echo "{{ azure_key }}" > /root/ch/azureApiKey

    # See https://learn.microsoft.com/en-us/azure/ai-services/speech-service/quickstarts/setup-platform?tabs=linux
    - name: Install OpenSSL 1.x
      shell: |
        set -e
        wget -O - https://www.openssl.org/source/openssl-1.1.1u.tar.gz | tar zxf -
        cd openssl-1.1.1u
        ./config --prefix=/usr/local
        make -j $(nproc)
        sudo make install_sw install_ssldirs
        sudo ldconfig -v

    - name: Render systemd service unit
      become: yes
      template:
        src: templates/yomichan-server.service
        dest: /etc/systemd/system/yomichan-server.service
        owner: root
        group: root

    - name: Render runner script
      become: yes
      template:
        src: templates/yomichan-server
        dest: /usr/local/bin/yomichan-server
        owner: root
        group: root
        mode: '0755'

    - name: Restart server
      become: yes
      systemd:
        name: yomichan-server
        daemon_reload: yes
        enabled: yes
        state: restarted


    # ---------------------------------------------------------------
    # NGINX
    # ---------------------------------------------------------------
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Ensure SSL directory exists
      file:
        path: /etc/nginx/ssl
        state: directory
        mode: '0755'

    - name: Generate a Self-Signed SSL Certificate
      command: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/nginx.key -out /etc/nginx/ssl/nginx.crt -subj "/CN=localhost"
      args:
        creates: /etc/nginx/ssl/nginx.crt

    - name: Remove default Nginx configuration
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Add Nginx reverse proxy configuration
      template:
        src: templates/yomichan_nginx.conf
        dest: /etc/nginx/sites-enabled/yomichan_nginx.conf

    - name: Ensure Nginx is running and enabled
      service:
        name: nginx
        state: restarted
        enabled: yes
